// <auto-generated />
using System;
using Medical.Server.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Medical.Persistence.Migrations
{
    [DbContext(typeof(PersistenceDataContext))]
    [Migration("20250210041756_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Medical.Domain.Entities.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdPacient")
                        .HasColumnType("int");

                    b.Property<int>("IdSpecialist")
                        .HasColumnType("int");

                    b.Property<int>("IdTreatment")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastModifiedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("TypeAppointmentId")
                        .HasColumnType("int");

                    b.Property<int>("TypeShiftId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdPacient");

                    b.HasIndex("IdSpecialist");

                    b.HasIndex("IdTreatment");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("Medical.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastModifiedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedUtc = new DateTime(2025, 2, 10, 4, 17, 55, 911, DateTimeKind.Utc).AddTicks(2564),
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Bienes",
                            Url = "bienes"
                        },
                        new
                        {
                            Id = 2,
                            CreatedUtc = new DateTime(2025, 2, 10, 4, 17, 55, 911, DateTimeKind.Utc).AddTicks(2575),
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Servicios",
                            Url = "servicios"
                        });
                });

            modelBuilder.Entity("Medical.Domain.Entities.Pacient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Birthdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastModifiedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumDocument")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TypeDocumentId")
                        .HasColumnType("int");

                    b.Property<int>("TypeSexId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NumDocument")
                        .IsUnique()
                        .HasFilter("[NumDocument] IS NOT NULL");

                    b.ToTable("Pacients");
                });

            modelBuilder.Entity("Medical.Domain.Entities.Specialist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Birthdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CollegeCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CollegeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastModifiedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumDocument")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfessionName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RneCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpecialtyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TypeDocumentId")
                        .HasColumnType("int");

                    b.Property<int>("TypeSexId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Specialists");
                });

            modelBuilder.Entity("Medical.Domain.Entities.Treatment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastModifiedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Treatments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cost = 0m,
                            CreatedUtc = new DateTime(2025, 2, 10, 4, 17, 55, 911, DateTimeKind.Utc).AddTicks(7379),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Ácido Hialurónico"
                        },
                        new
                        {
                            Id = 2,
                            Cost = 0m,
                            CreatedUtc = new DateTime(2025, 2, 10, 4, 17, 55, 911, DateTimeKind.Utc).AddTicks(7390),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Acupuntura"
                        },
                        new
                        {
                            Id = 3,
                            Cost = 0m,
                            CreatedUtc = new DateTime(2025, 2, 10, 4, 17, 55, 911, DateTimeKind.Utc).AddTicks(7392),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Autohemoterapia Mayor"
                        },
                        new
                        {
                            Id = 4,
                            Cost = 0m,
                            CreatedUtc = new DateTime(2025, 2, 10, 4, 17, 55, 911, DateTimeKind.Utc).AddTicks(7394),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Autohemoterapia Menor"
                        },
                        new
                        {
                            Id = 5,
                            Cost = 0m,
                            CreatedUtc = new DateTime(2025, 2, 10, 4, 17, 55, 911, DateTimeKind.Utc).AddTicks(7396),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Biodescodificación"
                        },
                        new
                        {
                            Id = 6,
                            Cost = 0m,
                            CreatedUtc = new DateTime(2025, 2, 10, 4, 17, 55, 911, DateTimeKind.Utc).AddTicks(7398),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Biomagnetismo"
                        },
                        new
                        {
                            Id = 7,
                            Cost = 0m,
                            CreatedUtc = new DateTime(2025, 2, 10, 4, 17, 55, 911, DateTimeKind.Utc).AddTicks(7402),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Botox"
                        },
                        new
                        {
                            Id = 8,
                            Cost = 0m,
                            CreatedUtc = new DateTime(2025, 2, 10, 4, 17, 55, 911, DateTimeKind.Utc).AddTicks(7404),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Consulta De Fitomedicina"
                        },
                        new
                        {
                            Id = 9,
                            Cost = 0m,
                            CreatedUtc = new DateTime(2025, 2, 10, 4, 17, 55, 911, DateTimeKind.Utc).AddTicks(7405),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Consulta Estética"
                        },
                        new
                        {
                            Id = 10,
                            Cost = 0m,
                            CreatedUtc = new DateTime(2025, 2, 10, 4, 17, 55, 911, DateTimeKind.Utc).AddTicks(7407),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Consulta Homeopática"
                        },
                        new
                        {
                            Id = 11,
                            Cost = 0m,
                            CreatedUtc = new DateTime(2025, 2, 10, 4, 17, 55, 911, DateTimeKind.Utc).AddTicks(7408),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Consulta Traumatología"
                        },
                        new
                        {
                            Id = 12,
                            Cost = 0m,
                            CreatedUtc = new DateTime(2025, 2, 10, 4, 17, 55, 911, DateTimeKind.Utc).AddTicks(7410),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Consulta Via Online"
                        },
                        new
                        {
                            Id = 13,
                            Cost = 0m,
                            CreatedUtc = new DateTime(2025, 2, 10, 4, 17, 55, 911, DateTimeKind.Utc).AddTicks(7411),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Control De Continuador"
                        },
                        new
                        {
                            Id = 14,
                            Cost = 0m,
                            CreatedUtc = new DateTime(2025, 2, 10, 4, 17, 55, 911, DateTimeKind.Utc).AddTicks(7413),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Control Prenatal"
                        },
                        new
                        {
                            Id = 15,
                            Cost = 0m,
                            CreatedUtc = new DateTime(2025, 2, 10, 4, 17, 55, 911, DateTimeKind.Utc).AddTicks(7414),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Digitupuntura"
                        },
                        new
                        {
                            Id = 16,
                            Cost = 0m,
                            CreatedUtc = new DateTime(2025, 2, 10, 4, 17, 55, 911, DateTimeKind.Utc).AddTicks(7415),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Drenaje Linfático"
                        },
                        new
                        {
                            Id = 17,
                            Cost = 0m,
                            CreatedUtc = new DateTime(2025, 2, 10, 4, 17, 55, 911, DateTimeKind.Utc).AddTicks(7417),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Ecografía"
                        },
                        new
                        {
                            Id = 18,
                            Cost = 0m,
                            CreatedUtc = new DateTime(2025, 2, 10, 4, 17, 55, 911, DateTimeKind.Utc).AddTicks(7418),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Electroestimulación Muscular"
                        },
                        new
                        {
                            Id = 19,
                            Cost = 0m,
                            CreatedUtc = new DateTime(2025, 2, 10, 4, 17, 55, 911, DateTimeKind.Utc).AddTicks(7419),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Gineco-Obstetricia"
                        },
                        new
                        {
                            Id = 20,
                            Cost = 0m,
                            CreatedUtc = new DateTime(2025, 2, 10, 4, 17, 55, 911, DateTimeKind.Utc).AddTicks(7421),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Hilos Tensores"
                        },
                        new
                        {
                            Id = 21,
                            Cost = 0m,
                            CreatedUtc = new DateTime(2025, 2, 10, 4, 17, 55, 911, DateTimeKind.Utc).AddTicks(7422),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Laboratorio Clínico"
                        },
                        new
                        {
                            Id = 22,
                            Cost = 0m,
                            CreatedUtc = new DateTime(2025, 2, 10, 4, 17, 55, 911, DateTimeKind.Utc).AddTicks(7423),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Lavado Y Ozonoterapia Vaginal"
                        },
                        new
                        {
                            Id = 23,
                            Cost = 0m,
                            CreatedUtc = new DateTime(2025, 2, 10, 4, 17, 55, 911, DateTimeKind.Utc).AddTicks(7424),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Limpieza Facial Profunda"
                        },
                        new
                        {
                            Id = 24,
                            Cost = 0m,
                            CreatedUtc = new DateTime(2025, 2, 10, 4, 17, 55, 911, DateTimeKind.Utc).AddTicks(7426),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Lipotransferencia"
                        },
                        new
                        {
                            Id = 25,
                            Cost = 0m,
                            CreatedUtc = new DateTime(2025, 2, 10, 4, 17, 55, 911, DateTimeKind.Utc).AddTicks(7427),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Magnetoterapia"
                        },
                        new
                        {
                            Id = 26,
                            Cost = 0m,
                            CreatedUtc = new DateTime(2025, 2, 10, 4, 17, 55, 911, DateTimeKind.Utc).AddTicks(7428),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Masaje Descontracturante"
                        },
                        new
                        {
                            Id = 27,
                            Cost = 0m,
                            CreatedUtc = new DateTime(2025, 2, 10, 4, 17, 55, 911, DateTimeKind.Utc).AddTicks(7430),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Masaje Reductor"
                        },
                        new
                        {
                            Id = 28,
                            Cost = 0m,
                            CreatedUtc = new DateTime(2025, 2, 10, 4, 17, 55, 911, DateTimeKind.Utc).AddTicks(7431),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Masaje Relajante"
                        },
                        new
                        {
                            Id = 29,
                            Cost = 0m,
                            CreatedUtc = new DateTime(2025, 2, 10, 4, 17, 55, 911, DateTimeKind.Utc).AddTicks(7432),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Ozonoterapia Rectal"
                        },
                        new
                        {
                            Id = 30,
                            Cost = 0m,
                            CreatedUtc = new DateTime(2025, 2, 10, 4, 17, 55, 911, DateTimeKind.Utc).AddTicks(7433),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Papanicolau"
                        },
                        new
                        {
                            Id = 31,
                            Cost = 0m,
                            CreatedUtc = new DateTime(2025, 2, 10, 4, 17, 55, 911, DateTimeKind.Utc).AddTicks(7502),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Peeling Químico"
                        },
                        new
                        {
                            Id = 32,
                            Cost = 0m,
                            CreatedUtc = new DateTime(2025, 2, 10, 4, 17, 55, 911, DateTimeKind.Utc).AddTicks(7504),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Peptonas"
                        },
                        new
                        {
                            Id = 33,
                            Cost = 0m,
                            CreatedUtc = new DateTime(2025, 2, 10, 4, 17, 55, 911, DateTimeKind.Utc).AddTicks(7505),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Plasma Rico En Plaquetas"
                        },
                        new
                        {
                            Id = 34,
                            Cost = 0m,
                            CreatedUtc = new DateTime(2025, 2, 10, 4, 17, 55, 911, DateTimeKind.Utc).AddTicks(7507),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Podología"
                        },
                        new
                        {
                            Id = 35,
                            Cost = 0m,
                            CreatedUtc = new DateTime(2025, 2, 10, 4, 17, 55, 911, DateTimeKind.Utc).AddTicks(7508),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Quiropraxia"
                        },
                        new
                        {
                            Id = 36,
                            Cost = 0m,
                            CreatedUtc = new DateTime(2025, 2, 10, 4, 17, 55, 911, DateTimeKind.Utc).AddTicks(7509),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Radiofrecuencia"
                        },
                        new
                        {
                            Id = 37,
                            Cost = 0m,
                            CreatedUtc = new DateTime(2025, 2, 10, 4, 17, 55, 911, DateTimeKind.Utc).AddTicks(7511),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Suero Ozonizado"
                        },
                        new
                        {
                            Id = 38,
                            Cost = 0m,
                            CreatedUtc = new DateTime(2025, 2, 10, 4, 17, 55, 911, DateTimeKind.Utc).AddTicks(7512),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Terapia De Vitaminas"
                        },
                        new
                        {
                            Id = 39,
                            Cost = 0m,
                            CreatedUtc = new DateTime(2025, 2, 10, 4, 17, 55, 911, DateTimeKind.Utc).AddTicks(7513),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Terapia Física Y Rehabilitación"
                        },
                        new
                        {
                            Id = 40,
                            Cost = 0m,
                            CreatedUtc = new DateTime(2025, 2, 10, 4, 17, 55, 911, DateTimeKind.Utc).AddTicks(7515),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Terapia Neural"
                        },
                        new
                        {
                            Id = 41,
                            Cost = 0m,
                            CreatedUtc = new DateTime(2025, 2, 10, 4, 17, 55, 911, DateTimeKind.Utc).AddTicks(7516),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Ultrasonido"
                        });
                });

            modelBuilder.Entity("Medical.Domain.Entities.TypeAppointment", b =>
                {
                    b.Property<int>("TypeAppointmentId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("TypeAppointmentId");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("[Name] IS NOT NULL");

                    b.ToTable("TypeAppointment");

                    b.HasData(
                        new
                        {
                            TypeAppointmentId = 0,
                            Name = "Consult"
                        },
                        new
                        {
                            TypeAppointmentId = 1,
                            Name = "Control"
                        });
                });

            modelBuilder.Entity("Medical.Domain.Entities.TypeDocument", b =>
                {
                    b.Property<int>("TypeDocumentId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("TypeDocumentId");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("[Name] IS NOT NULL");

                    b.ToTable("TypeDocument");

                    b.HasData(
                        new
                        {
                            TypeDocumentId = 0,
                            Name = "DNI"
                        },
                        new
                        {
                            TypeDocumentId = 1,
                            Name = "CI"
                        },
                        new
                        {
                            TypeDocumentId = 2,
                            Name = "CE"
                        },
                        new
                        {
                            TypeDocumentId = 3,
                            Name = "Passport"
                        });
                });

            modelBuilder.Entity("Medical.Domain.Entities.TypeSex", b =>
                {
                    b.Property<int>("TypeSexId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("TypeSexId");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("[Name] IS NOT NULL");

                    b.ToTable("TypeSex");

                    b.HasData(
                        new
                        {
                            TypeSexId = 0,
                            Name = "Female"
                        },
                        new
                        {
                            TypeSexId = 1,
                            Name = "Male"
                        });
                });

            modelBuilder.Entity("Medical.Domain.Entities.TypeShift", b =>
                {
                    b.Property<int>("TypeShiftId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("TypeShiftId");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("[Name] IS NOT NULL");

                    b.ToTable("TypeShift");

                    b.HasData(
                        new
                        {
                            TypeShiftId = 0,
                            Name = "Morning"
                        },
                        new
                        {
                            TypeShiftId = 1,
                            Name = "Afternoon"
                        },
                        new
                        {
                            TypeShiftId = 2,
                            Name = "Night"
                        });
                });

            modelBuilder.Entity("Medical.Domain.Entities.Appointment", b =>
                {
                    b.HasOne("Medical.Domain.Entities.Pacient", "Pacient")
                        .WithMany("Appointments")
                        .HasForeignKey("IdPacient")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Medical.Domain.Entities.Specialist", "Specialist")
                        .WithMany("Appointments")
                        .HasForeignKey("IdSpecialist")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Medical.Domain.Entities.Treatment", "Treatment")
                        .WithMany("Appointments")
                        .HasForeignKey("IdTreatment")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pacient");

                    b.Navigation("Specialist");

                    b.Navigation("Treatment");
                });

            modelBuilder.Entity("Medical.Domain.Entities.Pacient", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("Medical.Domain.Entities.Specialist", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("Medical.Domain.Entities.Treatment", b =>
                {
                    b.Navigation("Appointments");
                });
#pragma warning restore 612, 618
        }
    }
}
