// <auto-generated />
using System;
using Medical.Server.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Medical.Persistence.Migrations
{
    [DbContext(typeof(PersistenceDataContext))]
    [Migration("20250106000528_AddConsultorio")]
    partial class AddConsultorio
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Medical.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastModifiedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedUtc = new DateTime(2025, 1, 6, 0, 5, 27, 684, DateTimeKind.Utc).AddTicks(783),
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Bienes",
                            Url = "bienes"
                        },
                        new
                        {
                            Id = 2,
                            CreatedUtc = new DateTime(2025, 1, 6, 0, 5, 27, 684, DateTimeKind.Utc).AddTicks(790),
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Servicios",
                            Url = "servicios"
                        });
                });

            modelBuilder.Entity("Medical.Domain.Entities.Pacient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Birthdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastModifiedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumDocument")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TypeDocument")
                        .HasColumnType("int");

                    b.Property<int>("TypeSex")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NumDocument")
                        .IsUnique();

                    b.ToTable("Pacients");
                });

            modelBuilder.Entity("Medical.Domain.Entities.Treatment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastModifiedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Treatments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedUtc = new DateTime(2025, 1, 6, 0, 5, 27, 684, DateTimeKind.Utc).AddTicks(1992),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Ácido Hialurónico"
                        },
                        new
                        {
                            Id = 2,
                            CreatedUtc = new DateTime(2025, 1, 6, 0, 5, 27, 684, DateTimeKind.Utc).AddTicks(1994),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Acupuntura"
                        },
                        new
                        {
                            Id = 3,
                            CreatedUtc = new DateTime(2025, 1, 6, 0, 5, 27, 684, DateTimeKind.Utc).AddTicks(1995),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Autohemoterapia Mayor"
                        },
                        new
                        {
                            Id = 4,
                            CreatedUtc = new DateTime(2025, 1, 6, 0, 5, 27, 684, DateTimeKind.Utc).AddTicks(1996),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Autohemoterapia Menor"
                        },
                        new
                        {
                            Id = 5,
                            CreatedUtc = new DateTime(2025, 1, 6, 0, 5, 27, 684, DateTimeKind.Utc).AddTicks(1997),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Biodescodificación"
                        },
                        new
                        {
                            Id = 6,
                            CreatedUtc = new DateTime(2025, 1, 6, 0, 5, 27, 684, DateTimeKind.Utc).AddTicks(1998),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Biomagnetismo"
                        },
                        new
                        {
                            Id = 7,
                            CreatedUtc = new DateTime(2025, 1, 6, 0, 5, 27, 684, DateTimeKind.Utc).AddTicks(1999),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Botox"
                        },
                        new
                        {
                            Id = 8,
                            CreatedUtc = new DateTime(2025, 1, 6, 0, 5, 27, 684, DateTimeKind.Utc).AddTicks(2000),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Consulta De Fitomedicina"
                        },
                        new
                        {
                            Id = 9,
                            CreatedUtc = new DateTime(2025, 1, 6, 0, 5, 27, 684, DateTimeKind.Utc).AddTicks(2000),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Consulta Estética"
                        },
                        new
                        {
                            Id = 10,
                            CreatedUtc = new DateTime(2025, 1, 6, 0, 5, 27, 684, DateTimeKind.Utc).AddTicks(2001),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Consulta Homeopática"
                        },
                        new
                        {
                            Id = 11,
                            CreatedUtc = new DateTime(2025, 1, 6, 0, 5, 27, 684, DateTimeKind.Utc).AddTicks(2002),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Consulta Traumatología"
                        },
                        new
                        {
                            Id = 12,
                            CreatedUtc = new DateTime(2025, 1, 6, 0, 5, 27, 684, DateTimeKind.Utc).AddTicks(2003),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Consulta Via Online"
                        },
                        new
                        {
                            Id = 13,
                            CreatedUtc = new DateTime(2025, 1, 6, 0, 5, 27, 684, DateTimeKind.Utc).AddTicks(2004),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Control De Continuador"
                        },
                        new
                        {
                            Id = 14,
                            CreatedUtc = new DateTime(2025, 1, 6, 0, 5, 27, 684, DateTimeKind.Utc).AddTicks(2005),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Control Prenatal"
                        },
                        new
                        {
                            Id = 15,
                            CreatedUtc = new DateTime(2025, 1, 6, 0, 5, 27, 684, DateTimeKind.Utc).AddTicks(2006),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Digitupuntura"
                        },
                        new
                        {
                            Id = 16,
                            CreatedUtc = new DateTime(2025, 1, 6, 0, 5, 27, 684, DateTimeKind.Utc).AddTicks(2006),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Drenaje Linfático"
                        },
                        new
                        {
                            Id = 17,
                            CreatedUtc = new DateTime(2025, 1, 6, 0, 5, 27, 684, DateTimeKind.Utc).AddTicks(2007),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Ecografía"
                        },
                        new
                        {
                            Id = 18,
                            CreatedUtc = new DateTime(2025, 1, 6, 0, 5, 27, 684, DateTimeKind.Utc).AddTicks(2008),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Electroestimulación Muscular"
                        },
                        new
                        {
                            Id = 19,
                            CreatedUtc = new DateTime(2025, 1, 6, 0, 5, 27, 684, DateTimeKind.Utc).AddTicks(2009),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Gineco-Obstetricia"
                        },
                        new
                        {
                            Id = 20,
                            CreatedUtc = new DateTime(2025, 1, 6, 0, 5, 27, 684, DateTimeKind.Utc).AddTicks(2010),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Hilos Tensores"
                        },
                        new
                        {
                            Id = 21,
                            CreatedUtc = new DateTime(2025, 1, 6, 0, 5, 27, 684, DateTimeKind.Utc).AddTicks(2011),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Laboratorio Clínico"
                        },
                        new
                        {
                            Id = 22,
                            CreatedUtc = new DateTime(2025, 1, 6, 0, 5, 27, 684, DateTimeKind.Utc).AddTicks(2011),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Lavado Y Ozonoterapia Vaginal"
                        },
                        new
                        {
                            Id = 23,
                            CreatedUtc = new DateTime(2025, 1, 6, 0, 5, 27, 684, DateTimeKind.Utc).AddTicks(2012),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Limpieza Facial Profunda"
                        },
                        new
                        {
                            Id = 24,
                            CreatedUtc = new DateTime(2025, 1, 6, 0, 5, 27, 684, DateTimeKind.Utc).AddTicks(2013),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Lipotransferencia"
                        },
                        new
                        {
                            Id = 25,
                            CreatedUtc = new DateTime(2025, 1, 6, 0, 5, 27, 684, DateTimeKind.Utc).AddTicks(2014),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Magnetoterapia"
                        },
                        new
                        {
                            Id = 26,
                            CreatedUtc = new DateTime(2025, 1, 6, 0, 5, 27, 684, DateTimeKind.Utc).AddTicks(2014),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Masaje Descontracturante"
                        },
                        new
                        {
                            Id = 27,
                            CreatedUtc = new DateTime(2025, 1, 6, 0, 5, 27, 684, DateTimeKind.Utc).AddTicks(2015),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Masaje Reductor"
                        },
                        new
                        {
                            Id = 28,
                            CreatedUtc = new DateTime(2025, 1, 6, 0, 5, 27, 684, DateTimeKind.Utc).AddTicks(2016),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Masaje Relajante"
                        },
                        new
                        {
                            Id = 29,
                            CreatedUtc = new DateTime(2025, 1, 6, 0, 5, 27, 684, DateTimeKind.Utc).AddTicks(2017),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Ozonoterapia Rectal"
                        },
                        new
                        {
                            Id = 30,
                            CreatedUtc = new DateTime(2025, 1, 6, 0, 5, 27, 684, DateTimeKind.Utc).AddTicks(2018),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Papanicolau"
                        },
                        new
                        {
                            Id = 31,
                            CreatedUtc = new DateTime(2025, 1, 6, 0, 5, 27, 684, DateTimeKind.Utc).AddTicks(2018),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Peeling Químico"
                        },
                        new
                        {
                            Id = 32,
                            CreatedUtc = new DateTime(2025, 1, 6, 0, 5, 27, 684, DateTimeKind.Utc).AddTicks(2019),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Peptonas"
                        },
                        new
                        {
                            Id = 33,
                            CreatedUtc = new DateTime(2025, 1, 6, 0, 5, 27, 684, DateTimeKind.Utc).AddTicks(2020),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Plasma Rico En Plaquetas"
                        },
                        new
                        {
                            Id = 34,
                            CreatedUtc = new DateTime(2025, 1, 6, 0, 5, 27, 684, DateTimeKind.Utc).AddTicks(2021),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Podología"
                        },
                        new
                        {
                            Id = 35,
                            CreatedUtc = new DateTime(2025, 1, 6, 0, 5, 27, 684, DateTimeKind.Utc).AddTicks(2021),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Quiropraxia"
                        },
                        new
                        {
                            Id = 36,
                            CreatedUtc = new DateTime(2025, 1, 6, 0, 5, 27, 684, DateTimeKind.Utc).AddTicks(2022),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Radiofrecuencia"
                        },
                        new
                        {
                            Id = 37,
                            CreatedUtc = new DateTime(2025, 1, 6, 0, 5, 27, 684, DateTimeKind.Utc).AddTicks(2023),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Suero Ozonizado"
                        },
                        new
                        {
                            Id = 38,
                            CreatedUtc = new DateTime(2025, 1, 6, 0, 5, 27, 684, DateTimeKind.Utc).AddTicks(2024),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Terapia De Vitaminas"
                        },
                        new
                        {
                            Id = 39,
                            CreatedUtc = new DateTime(2025, 1, 6, 0, 5, 27, 684, DateTimeKind.Utc).AddTicks(2025),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Terapia Física Y Rehabilitación"
                        },
                        new
                        {
                            Id = 40,
                            CreatedUtc = new DateTime(2025, 1, 6, 0, 5, 27, 684, DateTimeKind.Utc).AddTicks(2025),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Terapia Neural"
                        },
                        new
                        {
                            Id = 41,
                            CreatedUtc = new DateTime(2025, 1, 6, 0, 5, 27, 684, DateTimeKind.Utc).AddTicks(2026),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Ultrasonido"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
