// <auto-generated />
using System;
using Medical.Server.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Medical.Persistence.Migrations
{
    [DbContext(typeof(PersistenceDataContext))]
    [Migration("20250107083616_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Medical.Domain.Entities.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdPacient")
                        .HasColumnType("int");

                    b.Property<int>("IdSpecialist")
                        .HasColumnType("int");

                    b.Property<int>("IdTreatment")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastModifiedUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("TypeAppointmentId")
                        .HasColumnType("int");

                    b.Property<int>("TypeShiftId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdPacient");

                    b.HasIndex("IdSpecialist");

                    b.HasIndex("IdTreatment");

                    b.HasIndex("TypeAppointmentId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("Medical.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastModifiedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedUtc = new DateTime(2025, 1, 7, 8, 36, 15, 619, DateTimeKind.Utc).AddTicks(2936),
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Bienes",
                            Url = "bienes"
                        },
                        new
                        {
                            Id = 2,
                            CreatedUtc = new DateTime(2025, 1, 7, 8, 36, 15, 619, DateTimeKind.Utc).AddTicks(2945),
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Servicios",
                            Url = "servicios"
                        });
                });

            modelBuilder.Entity("Medical.Domain.Entities.Pacient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Birthdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastModifiedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumDocument")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TypeDocumentId")
                        .HasColumnType("int");

                    b.Property<int>("TypeSexId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NumDocument")
                        .IsUnique();

                    b.ToTable("Pacients");
                });

            modelBuilder.Entity("Medical.Domain.Entities.Specialist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Birthdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CollegeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CollegeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastModifiedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumDocument")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpecialtyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TypeDocumentId")
                        .HasColumnType("int");

                    b.Property<int>("TypeSexId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Specialists");
                });

            modelBuilder.Entity("Medical.Domain.Entities.Treatment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastModifiedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Treatments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedUtc = new DateTime(2025, 1, 7, 8, 36, 15, 619, DateTimeKind.Utc).AddTicks(6652),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Ácido Hialurónico"
                        },
                        new
                        {
                            Id = 2,
                            CreatedUtc = new DateTime(2025, 1, 7, 8, 36, 15, 619, DateTimeKind.Utc).AddTicks(6656),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Acupuntura"
                        },
                        new
                        {
                            Id = 3,
                            CreatedUtc = new DateTime(2025, 1, 7, 8, 36, 15, 619, DateTimeKind.Utc).AddTicks(6657),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Autohemoterapia Mayor"
                        },
                        new
                        {
                            Id = 4,
                            CreatedUtc = new DateTime(2025, 1, 7, 8, 36, 15, 619, DateTimeKind.Utc).AddTicks(6659),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Autohemoterapia Menor"
                        },
                        new
                        {
                            Id = 5,
                            CreatedUtc = new DateTime(2025, 1, 7, 8, 36, 15, 619, DateTimeKind.Utc).AddTicks(6660),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Biodescodificación"
                        },
                        new
                        {
                            Id = 6,
                            CreatedUtc = new DateTime(2025, 1, 7, 8, 36, 15, 619, DateTimeKind.Utc).AddTicks(6661),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Biomagnetismo"
                        },
                        new
                        {
                            Id = 7,
                            CreatedUtc = new DateTime(2025, 1, 7, 8, 36, 15, 619, DateTimeKind.Utc).AddTicks(6662),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Botox"
                        },
                        new
                        {
                            Id = 8,
                            CreatedUtc = new DateTime(2025, 1, 7, 8, 36, 15, 619, DateTimeKind.Utc).AddTicks(6663),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Consulta De Fitomedicina"
                        },
                        new
                        {
                            Id = 9,
                            CreatedUtc = new DateTime(2025, 1, 7, 8, 36, 15, 619, DateTimeKind.Utc).AddTicks(6664),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Consulta Estética"
                        },
                        new
                        {
                            Id = 10,
                            CreatedUtc = new DateTime(2025, 1, 7, 8, 36, 15, 619, DateTimeKind.Utc).AddTicks(6665),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Consulta Homeopática"
                        },
                        new
                        {
                            Id = 11,
                            CreatedUtc = new DateTime(2025, 1, 7, 8, 36, 15, 619, DateTimeKind.Utc).AddTicks(6666),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Consulta Traumatología"
                        },
                        new
                        {
                            Id = 12,
                            CreatedUtc = new DateTime(2025, 1, 7, 8, 36, 15, 619, DateTimeKind.Utc).AddTicks(6667),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Consulta Via Online"
                        },
                        new
                        {
                            Id = 13,
                            CreatedUtc = new DateTime(2025, 1, 7, 8, 36, 15, 619, DateTimeKind.Utc).AddTicks(6668),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Control De Continuador"
                        },
                        new
                        {
                            Id = 14,
                            CreatedUtc = new DateTime(2025, 1, 7, 8, 36, 15, 619, DateTimeKind.Utc).AddTicks(6669),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Control Prenatal"
                        },
                        new
                        {
                            Id = 15,
                            CreatedUtc = new DateTime(2025, 1, 7, 8, 36, 15, 619, DateTimeKind.Utc).AddTicks(6670),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Digitupuntura"
                        },
                        new
                        {
                            Id = 16,
                            CreatedUtc = new DateTime(2025, 1, 7, 8, 36, 15, 619, DateTimeKind.Utc).AddTicks(6671),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Drenaje Linfático"
                        },
                        new
                        {
                            Id = 17,
                            CreatedUtc = new DateTime(2025, 1, 7, 8, 36, 15, 619, DateTimeKind.Utc).AddTicks(6672),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Ecografía"
                        },
                        new
                        {
                            Id = 18,
                            CreatedUtc = new DateTime(2025, 1, 7, 8, 36, 15, 619, DateTimeKind.Utc).AddTicks(6673),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Electroestimulación Muscular"
                        },
                        new
                        {
                            Id = 19,
                            CreatedUtc = new DateTime(2025, 1, 7, 8, 36, 15, 619, DateTimeKind.Utc).AddTicks(6674),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Gineco-Obstetricia"
                        },
                        new
                        {
                            Id = 20,
                            CreatedUtc = new DateTime(2025, 1, 7, 8, 36, 15, 619, DateTimeKind.Utc).AddTicks(6675),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Hilos Tensores"
                        },
                        new
                        {
                            Id = 21,
                            CreatedUtc = new DateTime(2025, 1, 7, 8, 36, 15, 619, DateTimeKind.Utc).AddTicks(6676),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Laboratorio Clínico"
                        },
                        new
                        {
                            Id = 22,
                            CreatedUtc = new DateTime(2025, 1, 7, 8, 36, 15, 619, DateTimeKind.Utc).AddTicks(6677),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Lavado Y Ozonoterapia Vaginal"
                        },
                        new
                        {
                            Id = 23,
                            CreatedUtc = new DateTime(2025, 1, 7, 8, 36, 15, 619, DateTimeKind.Utc).AddTicks(6678),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Limpieza Facial Profunda"
                        },
                        new
                        {
                            Id = 24,
                            CreatedUtc = new DateTime(2025, 1, 7, 8, 36, 15, 619, DateTimeKind.Utc).AddTicks(6679),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Lipotransferencia"
                        },
                        new
                        {
                            Id = 25,
                            CreatedUtc = new DateTime(2025, 1, 7, 8, 36, 15, 619, DateTimeKind.Utc).AddTicks(6680),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Magnetoterapia"
                        },
                        new
                        {
                            Id = 26,
                            CreatedUtc = new DateTime(2025, 1, 7, 8, 36, 15, 619, DateTimeKind.Utc).AddTicks(6681),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Masaje Descontracturante"
                        },
                        new
                        {
                            Id = 27,
                            CreatedUtc = new DateTime(2025, 1, 7, 8, 36, 15, 619, DateTimeKind.Utc).AddTicks(6682),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Masaje Reductor"
                        },
                        new
                        {
                            Id = 28,
                            CreatedUtc = new DateTime(2025, 1, 7, 8, 36, 15, 619, DateTimeKind.Utc).AddTicks(6683),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Masaje Relajante"
                        },
                        new
                        {
                            Id = 29,
                            CreatedUtc = new DateTime(2025, 1, 7, 8, 36, 15, 619, DateTimeKind.Utc).AddTicks(6684),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Ozonoterapia Rectal"
                        },
                        new
                        {
                            Id = 30,
                            CreatedUtc = new DateTime(2025, 1, 7, 8, 36, 15, 619, DateTimeKind.Utc).AddTicks(6685),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Papanicolau"
                        },
                        new
                        {
                            Id = 31,
                            CreatedUtc = new DateTime(2025, 1, 7, 8, 36, 15, 619, DateTimeKind.Utc).AddTicks(6686),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Peeling Químico"
                        },
                        new
                        {
                            Id = 32,
                            CreatedUtc = new DateTime(2025, 1, 7, 8, 36, 15, 619, DateTimeKind.Utc).AddTicks(6687),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Peptonas"
                        },
                        new
                        {
                            Id = 33,
                            CreatedUtc = new DateTime(2025, 1, 7, 8, 36, 15, 619, DateTimeKind.Utc).AddTicks(6688),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Plasma Rico En Plaquetas"
                        },
                        new
                        {
                            Id = 34,
                            CreatedUtc = new DateTime(2025, 1, 7, 8, 36, 15, 619, DateTimeKind.Utc).AddTicks(6689),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Podología"
                        },
                        new
                        {
                            Id = 35,
                            CreatedUtc = new DateTime(2025, 1, 7, 8, 36, 15, 619, DateTimeKind.Utc).AddTicks(6690),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Quiropraxia"
                        },
                        new
                        {
                            Id = 36,
                            CreatedUtc = new DateTime(2025, 1, 7, 8, 36, 15, 619, DateTimeKind.Utc).AddTicks(6691),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Radiofrecuencia"
                        },
                        new
                        {
                            Id = 37,
                            CreatedUtc = new DateTime(2025, 1, 7, 8, 36, 15, 619, DateTimeKind.Utc).AddTicks(6692),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Suero Ozonizado"
                        },
                        new
                        {
                            Id = 38,
                            CreatedUtc = new DateTime(2025, 1, 7, 8, 36, 15, 619, DateTimeKind.Utc).AddTicks(6693),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Terapia De Vitaminas"
                        },
                        new
                        {
                            Id = 39,
                            CreatedUtc = new DateTime(2025, 1, 7, 8, 36, 15, 619, DateTimeKind.Utc).AddTicks(6695),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Terapia Física Y Rehabilitación"
                        },
                        new
                        {
                            Id = 40,
                            CreatedUtc = new DateTime(2025, 1, 7, 8, 36, 15, 619, DateTimeKind.Utc).AddTicks(6695),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Terapia Neural"
                        },
                        new
                        {
                            Id = 41,
                            CreatedUtc = new DateTime(2025, 1, 7, 8, 36, 15, 619, DateTimeKind.Utc).AddTicks(6696),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Ultrasonido"
                        });
                });

            modelBuilder.Entity("Medical.Domain.Entities.TypeAppointment", b =>
                {
                    b.Property<int>("TypeAppointmentId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("TypeAppointmentId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("TypeAppointment");

                    b.HasData(
                        new
                        {
                            TypeAppointmentId = 0,
                            Name = "None"
                        },
                        new
                        {
                            TypeAppointmentId = 1,
                            Name = "Consulta"
                        },
                        new
                        {
                            TypeAppointmentId = 2,
                            Name = "Control"
                        });
                });

            modelBuilder.Entity("Medical.Domain.Entities.TypeDocument", b =>
                {
                    b.Property<int>("TypeDocumentId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("TypeDocumentId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("TypeDocument");

                    b.HasData(
                        new
                        {
                            TypeDocumentId = 0,
                            Name = "None"
                        },
                        new
                        {
                            TypeDocumentId = 1,
                            Name = "DNI"
                        },
                        new
                        {
                            TypeDocumentId = 2,
                            Name = "CI"
                        },
                        new
                        {
                            TypeDocumentId = 3,
                            Name = "CE"
                        },
                        new
                        {
                            TypeDocumentId = 4,
                            Name = "Pasaporte"
                        });
                });

            modelBuilder.Entity("Medical.Domain.Entities.TypeSex", b =>
                {
                    b.Property<int>("TypeSexId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("TypeSexId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("TypeSex");

                    b.HasData(
                        new
                        {
                            TypeSexId = 0,
                            Name = "None"
                        },
                        new
                        {
                            TypeSexId = 1,
                            Name = "Femenino"
                        },
                        new
                        {
                            TypeSexId = 2,
                            Name = "Masculino"
                        });
                });

            modelBuilder.Entity("Medical.Domain.Entities.TypeShift", b =>
                {
                    b.Property<int>("TypeShiftId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("TypeShiftId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("TypeShift");

                    b.HasData(
                        new
                        {
                            TypeShiftId = 0,
                            Name = "None"
                        },
                        new
                        {
                            TypeShiftId = 1,
                            Name = "Dia"
                        },
                        new
                        {
                            TypeShiftId = 2,
                            Name = "Tarde"
                        },
                        new
                        {
                            TypeShiftId = 3,
                            Name = "Noche"
                        });
                });

            modelBuilder.Entity("Medical.Domain.Entities.Appointment", b =>
                {
                    b.HasOne("Medical.Domain.Entities.Pacient", "Pacient")
                        .WithMany("Appointments")
                        .HasForeignKey("IdPacient")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Medical.Domain.Entities.Specialist", "Specialist")
                        .WithMany("Appointments")
                        .HasForeignKey("IdSpecialist")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Medical.Domain.Entities.Treatment", "Treatment")
                        .WithMany("Appointments")
                        .HasForeignKey("IdTreatment")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Medical.Domain.Entities.TypeAppointment", "TypeAppointment")
                        .WithMany()
                        .HasForeignKey("TypeAppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pacient");

                    b.Navigation("Specialist");

                    b.Navigation("Treatment");

                    b.Navigation("TypeAppointment");
                });

            modelBuilder.Entity("Medical.Domain.Entities.Pacient", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("Medical.Domain.Entities.Specialist", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("Medical.Domain.Entities.Treatment", b =>
                {
                    b.Navigation("Appointments");
                });
#pragma warning restore 612, 618
        }
    }
}
