// <auto-generated />
using System;
using Medical.Server.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Medical.Persistence.Migrations
{
    [DbContext(typeof(PersistenceDataContext))]
    [Migration("20250216163219_AddFiscalUnitRows")]
    partial class AddFiscalUnitRows
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Medical.Domain.Entities.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdPacient")
                        .HasColumnType("int");

                    b.Property<int>("IdSpecialist")
                        .HasColumnType("int");

                    b.Property<int>("IdTreatment")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastModifiedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("TypeAppointmentId")
                        .HasColumnType("int");

                    b.Property<int>("TypeShiftId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdPacient");

                    b.HasIndex("IdSpecialist");

                    b.HasIndex("IdTreatment");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("Medical.Domain.Entities.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastModifiedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Brands");
                });

            modelBuilder.Entity("Medical.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastModifiedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedUtc = new DateTime(2025, 2, 16, 16, 32, 18, 525, DateTimeKind.Utc).AddTicks(4468),
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Bienes",
                            Url = "bienes"
                        },
                        new
                        {
                            Id = 2,
                            CreatedUtc = new DateTime(2025, 2, 16, 16, 32, 18, 525, DateTimeKind.Utc).AddTicks(4472),
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Servicios",
                            Url = "servicios"
                        });
                });

            modelBuilder.Entity("Medical.Domain.Entities.FiscalUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastModifiedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FiscalUnits");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "NIU",
                            CreatedUtc = new DateTime(2025, 2, 16, 16, 32, 18, 525, DateTimeKind.Utc).AddTicks(5570),
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "UNIDAD"
                        },
                        new
                        {
                            Id = 2,
                            Code = "MMT",
                            CreatedUtc = new DateTime(2025, 2, 16, 16, 32, 18, 525, DateTimeKind.Utc).AddTicks(5572),
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "MILIMETRO"
                        },
                        new
                        {
                            Id = 3,
                            Code = "MMK",
                            CreatedUtc = new DateTime(2025, 2, 16, 16, 32, 18, 525, DateTimeKind.Utc).AddTicks(5573),
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "MILIMETRO CUADRADO"
                        },
                        new
                        {
                            Id = 4,
                            Code = "MMQ",
                            CreatedUtc = new DateTime(2025, 2, 16, 16, 32, 18, 525, DateTimeKind.Utc).AddTicks(5574),
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "MILIMETRO CUBICO"
                        },
                        new
                        {
                            Id = 5,
                            Code = "MIL",
                            CreatedUtc = new DateTime(2025, 2, 16, 16, 32, 18, 525, DateTimeKind.Utc).AddTicks(5575),
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "MILLARES"
                        },
                        new
                        {
                            Id = 6,
                            Code = "UM",
                            CreatedUtc = new DateTime(2025, 2, 16, 16, 32, 18, 525, DateTimeKind.Utc).AddTicks(5576),
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "MILLON DE UNIDADES"
                        },
                        new
                        {
                            Id = 7,
                            Code = "ONZ",
                            CreatedUtc = new DateTime(2025, 2, 16, 16, 32, 18, 525, DateTimeKind.Utc).AddTicks(5577),
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "ONZAS"
                        },
                        new
                        {
                            Id = 8,
                            Code = "PF",
                            CreatedUtc = new DateTime(2025, 2, 16, 16, 32, 18, 525, DateTimeKind.Utc).AddTicks(5637),
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "PALETAS"
                        },
                        new
                        {
                            Id = 9,
                            Code = "PK",
                            CreatedUtc = new DateTime(2025, 2, 16, 16, 32, 18, 525, DateTimeKind.Utc).AddTicks(5638),
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "PAQUETE"
                        },
                        new
                        {
                            Id = 10,
                            Code = "PR",
                            CreatedUtc = new DateTime(2025, 2, 16, 16, 32, 18, 525, DateTimeKind.Utc).AddTicks(5639),
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "PAR"
                        },
                        new
                        {
                            Id = 11,
                            Code = "FOT",
                            CreatedUtc = new DateTime(2025, 2, 16, 16, 32, 18, 525, DateTimeKind.Utc).AddTicks(5640),
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "PIES"
                        },
                        new
                        {
                            Id = 12,
                            Code = "FTK",
                            CreatedUtc = new DateTime(2025, 2, 16, 16, 32, 18, 525, DateTimeKind.Utc).AddTicks(5640),
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "PIES CUADRADOS"
                        },
                        new
                        {
                            Id = 13,
                            Code = "FTQ",
                            CreatedUtc = new DateTime(2025, 2, 16, 16, 32, 18, 525, DateTimeKind.Utc).AddTicks(5641),
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "PIES CUBICOS"
                        },
                        new
                        {
                            Id = 14,
                            Code = "C62",
                            CreatedUtc = new DateTime(2025, 2, 16, 16, 32, 18, 525, DateTimeKind.Utc).AddTicks(5642),
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "PIEZAS"
                        },
                        new
                        {
                            Id = 15,
                            Code = "PG",
                            CreatedUtc = new DateTime(2025, 2, 16, 16, 32, 18, 525, DateTimeKind.Utc).AddTicks(5643),
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "PLACAS"
                        },
                        new
                        {
                            Id = 16,
                            Code = "ST",
                            CreatedUtc = new DateTime(2025, 2, 16, 16, 32, 18, 525, DateTimeKind.Utc).AddTicks(5644),
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "PLIEGO"
                        },
                        new
                        {
                            Id = 17,
                            Code = "INH",
                            CreatedUtc = new DateTime(2025, 2, 16, 16, 32, 18, 525, DateTimeKind.Utc).AddTicks(5645),
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "PULGADAS"
                        },
                        new
                        {
                            Id = 18,
                            Code = "RM",
                            CreatedUtc = new DateTime(2025, 2, 16, 16, 32, 18, 525, DateTimeKind.Utc).AddTicks(5645),
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "RESMA"
                        },
                        new
                        {
                            Id = 19,
                            Code = "DR",
                            CreatedUtc = new DateTime(2025, 2, 16, 16, 32, 18, 525, DateTimeKind.Utc).AddTicks(5646),
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "TAMBOR"
                        },
                        new
                        {
                            Id = 20,
                            Code = "STN",
                            CreatedUtc = new DateTime(2025, 2, 16, 16, 32, 18, 525, DateTimeKind.Utc).AddTicks(5647),
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "TONELADA CORTA"
                        },
                        new
                        {
                            Id = 21,
                            Code = "LTN",
                            CreatedUtc = new DateTime(2025, 2, 16, 16, 32, 18, 525, DateTimeKind.Utc).AddTicks(5648),
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "TONELADA LARGA"
                        },
                        new
                        {
                            Id = 22,
                            Code = "TNE",
                            CreatedUtc = new DateTime(2025, 2, 16, 16, 32, 18, 525, DateTimeKind.Utc).AddTicks(5649),
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "TONELADAS"
                        },
                        new
                        {
                            Id = 23,
                            Code = "TU",
                            CreatedUtc = new DateTime(2025, 2, 16, 16, 32, 18, 525, DateTimeKind.Utc).AddTicks(5650),
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "TUBOS"
                        },
                        new
                        {
                            Id = 24,
                            Code = "ZZ",
                            CreatedUtc = new DateTime(2025, 2, 16, 16, 32, 18, 525, DateTimeKind.Utc).AddTicks(5650),
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "UNIDAD (SERVICIOS)"
                        },
                        new
                        {
                            Id = 25,
                            Code = "GLL",
                            CreatedUtc = new DateTime(2025, 2, 16, 16, 32, 18, 525, DateTimeKind.Utc).AddTicks(5651),
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "US GALON (3,78L)"
                        },
                        new
                        {
                            Id = 26,
                            Code = "YRD",
                            CreatedUtc = new DateTime(2025, 2, 16, 16, 32, 18, 525, DateTimeKind.Utc).AddTicks(5652),
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "YARDA"
                        },
                        new
                        {
                            Id = 27,
                            Code = "YDK",
                            CreatedUtc = new DateTime(2025, 2, 16, 16, 32, 18, 525, DateTimeKind.Utc).AddTicks(5653),
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "YARDA CUADRADA"
                        },
                        new
                        {
                            Id = 28,
                            Code = "MLT",
                            CreatedUtc = new DateTime(2025, 2, 16, 16, 32, 18, 525, DateTimeKind.Utc).AddTicks(5654),
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "MILILITRO"
                        },
                        new
                        {
                            Id = 29,
                            Code = "MGM",
                            CreatedUtc = new DateTime(2025, 2, 16, 16, 32, 18, 525, DateTimeKind.Utc).AddTicks(5654),
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "MILIGRAMOS"
                        },
                        new
                        {
                            Id = 30,
                            Code = "MTQ",
                            CreatedUtc = new DateTime(2025, 2, 16, 16, 32, 18, 525, DateTimeKind.Utc).AddTicks(5655),
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "METRO CUBICO"
                        },
                        new
                        {
                            Id = 31,
                            Code = "MTK",
                            CreatedUtc = new DateTime(2025, 2, 16, 16, 32, 18, 525, DateTimeKind.Utc).AddTicks(5656),
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "METRO CUADRADO"
                        },
                        new
                        {
                            Id = 32,
                            Code = "MTR",
                            CreatedUtc = new DateTime(2025, 2, 16, 16, 32, 18, 525, DateTimeKind.Utc).AddTicks(5657),
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "METRO"
                        },
                        new
                        {
                            Id = 33,
                            Code = "4A",
                            CreatedUtc = new DateTime(2025, 2, 16, 16, 32, 18, 525, DateTimeKind.Utc).AddTicks(5658),
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "BOBINAS"
                        },
                        new
                        {
                            Id = 34,
                            Code = "BJ",
                            CreatedUtc = new DateTime(2025, 2, 16, 16, 32, 18, 525, DateTimeKind.Utc).AddTicks(5658),
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "BALDE"
                        },
                        new
                        {
                            Id = 35,
                            Code = "BLL",
                            CreatedUtc = new DateTime(2025, 2, 16, 16, 32, 18, 525, DateTimeKind.Utc).AddTicks(5659),
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "BARRILES"
                        },
                        new
                        {
                            Id = 36,
                            Code = "BG",
                            CreatedUtc = new DateTime(2025, 2, 16, 16, 32, 18, 525, DateTimeKind.Utc).AddTicks(5660),
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "BOLSA"
                        },
                        new
                        {
                            Id = 37,
                            Code = "BO",
                            CreatedUtc = new DateTime(2025, 2, 16, 16, 32, 18, 525, DateTimeKind.Utc).AddTicks(5661),
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "BOTELLAS"
                        },
                        new
                        {
                            Id = 38,
                            Code = "BX",
                            CreatedUtc = new DateTime(2025, 2, 16, 16, 32, 18, 525, DateTimeKind.Utc).AddTicks(5661),
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "CAJA"
                        },
                        new
                        {
                            Id = 39,
                            Code = "CT",
                            CreatedUtc = new DateTime(2025, 2, 16, 16, 32, 18, 525, DateTimeKind.Utc).AddTicks(5662),
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "CARTONES"
                        },
                        new
                        {
                            Id = 40,
                            Code = "CMK",
                            CreatedUtc = new DateTime(2025, 2, 16, 16, 32, 18, 525, DateTimeKind.Utc).AddTicks(5663),
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "CENTIMETRO CUADRADO"
                        },
                        new
                        {
                            Id = 41,
                            Code = "CMQ",
                            CreatedUtc = new DateTime(2025, 2, 16, 16, 32, 18, 525, DateTimeKind.Utc).AddTicks(5664),
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "CENTIMETRO CUBICO"
                        },
                        new
                        {
                            Id = 42,
                            Code = "CMT",
                            CreatedUtc = new DateTime(2025, 2, 16, 16, 32, 18, 525, DateTimeKind.Utc).AddTicks(5664),
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "CENTIMETRO LINEAL"
                        },
                        new
                        {
                            Id = 43,
                            Code = "CEN",
                            CreatedUtc = new DateTime(2025, 2, 16, 16, 32, 18, 525, DateTimeKind.Utc).AddTicks(5665),
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "CIENTO DE UNIDADES"
                        },
                        new
                        {
                            Id = 44,
                            Code = "CY",
                            CreatedUtc = new DateTime(2025, 2, 16, 16, 32, 18, 525, DateTimeKind.Utc).AddTicks(5666),
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "CILINDRO"
                        },
                        new
                        {
                            Id = 45,
                            Code = "CJ",
                            CreatedUtc = new DateTime(2025, 2, 16, 16, 32, 18, 525, DateTimeKind.Utc).AddTicks(5667),
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "CONOS"
                        },
                        new
                        {
                            Id = 46,
                            Code = "DZN",
                            CreatedUtc = new DateTime(2025, 2, 16, 16, 32, 18, 525, DateTimeKind.Utc).AddTicks(5668),
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "DOCENA"
                        },
                        new
                        {
                            Id = 47,
                            Code = "DZP",
                            CreatedUtc = new DateTime(2025, 2, 16, 16, 32, 18, 525, DateTimeKind.Utc).AddTicks(5669),
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "DOCENA POR 10**6"
                        },
                        new
                        {
                            Id = 48,
                            Code = "BE",
                            CreatedUtc = new DateTime(2025, 2, 16, 16, 32, 18, 525, DateTimeKind.Utc).AddTicks(5669),
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "FARDO"
                        },
                        new
                        {
                            Id = 49,
                            Code = "GLI",
                            CreatedUtc = new DateTime(2025, 2, 16, 16, 32, 18, 525, DateTimeKind.Utc).AddTicks(5670),
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "GALON INGLES (4,54L)"
                        },
                        new
                        {
                            Id = 50,
                            Code = "GRM",
                            CreatedUtc = new DateTime(2025, 2, 16, 16, 32, 18, 525, DateTimeKind.Utc).AddTicks(5671),
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "GRAMO"
                        },
                        new
                        {
                            Id = 51,
                            Code = "GRO",
                            CreatedUtc = new DateTime(2025, 2, 16, 16, 32, 18, 525, DateTimeKind.Utc).AddTicks(5672),
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "GRUESA"
                        },
                        new
                        {
                            Id = 52,
                            Code = "HLT",
                            CreatedUtc = new DateTime(2025, 2, 16, 16, 32, 18, 525, DateTimeKind.Utc).AddTicks(5673),
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "HECTOLITRO"
                        },
                        new
                        {
                            Id = 53,
                            Code = "LEF",
                            CreatedUtc = new DateTime(2025, 2, 16, 16, 32, 18, 525, DateTimeKind.Utc).AddTicks(5674),
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "HOJA"
                        },
                        new
                        {
                            Id = 54,
                            Code = "KGM",
                            CreatedUtc = new DateTime(2025, 2, 16, 16, 32, 18, 525, DateTimeKind.Utc).AddTicks(5674),
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "KILOGRAMO"
                        },
                        new
                        {
                            Id = 55,
                            Code = "KTM",
                            CreatedUtc = new DateTime(2025, 2, 16, 16, 32, 18, 525, DateTimeKind.Utc).AddTicks(5675),
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "KILOMETRO"
                        },
                        new
                        {
                            Id = 56,
                            Code = "KWM",
                            CreatedUtc = new DateTime(2025, 2, 16, 16, 32, 18, 525, DateTimeKind.Utc).AddTicks(5676),
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "KILOVATIO HORA"
                        },
                        new
                        {
                            Id = 57,
                            Code = "KT",
                            CreatedUtc = new DateTime(2025, 2, 16, 16, 32, 18, 525, DateTimeKind.Utc).AddTicks(5677),
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "kit"
                        },
                        new
                        {
                            Id = 58,
                            Code = "CA",
                            CreatedUtc = new DateTime(2025, 2, 16, 16, 32, 18, 525, DateTimeKind.Utc).AddTicks(5677),
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "LATAS"
                        },
                        new
                        {
                            Id = 59,
                            Code = "LBR",
                            CreatedUtc = new DateTime(2025, 2, 16, 16, 32, 18, 525, DateTimeKind.Utc).AddTicks(5678),
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "LIBRAS"
                        },
                        new
                        {
                            Id = 60,
                            Code = "LTR",
                            CreatedUtc = new DateTime(2025, 2, 16, 16, 32, 18, 525, DateTimeKind.Utc).AddTicks(5679),
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "LITRO"
                        },
                        new
                        {
                            Id = 61,
                            Code = "MWH",
                            CreatedUtc = new DateTime(2025, 2, 16, 16, 32, 18, 525, DateTimeKind.Utc).AddTicks(5680),
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "MEGAWATT HORA"
                        });
                });

            modelBuilder.Entity("Medical.Domain.Entities.Pacient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Birthdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastModifiedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumDocument")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TypeDocumentId")
                        .HasColumnType("int");

                    b.Property<int>("TypeSexId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NumDocument")
                        .IsUnique()
                        .HasFilter("[NumDocument] IS NOT NULL");

                    b.ToTable("Pacients");
                });

            modelBuilder.Entity("Medical.Domain.Entities.Specialist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Birthdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CollegeCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CollegeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastModifiedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumDocument")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfessionName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RneCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpecialtyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TypeDocumentId")
                        .HasColumnType("int");

                    b.Property<int>("TypeSexId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Specialists");
                });

            modelBuilder.Entity("Medical.Domain.Entities.Treatment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastModifiedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Treatments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cost = 1m,
                            CreatedUtc = new DateTime(2025, 2, 16, 16, 32, 18, 525, DateTimeKind.Utc).AddTicks(8329),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Ácido Hialurónico"
                        },
                        new
                        {
                            Id = 2,
                            Cost = 1m,
                            CreatedUtc = new DateTime(2025, 2, 16, 16, 32, 18, 525, DateTimeKind.Utc).AddTicks(8331),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Acupuntura"
                        },
                        new
                        {
                            Id = 3,
                            Cost = 1m,
                            CreatedUtc = new DateTime(2025, 2, 16, 16, 32, 18, 525, DateTimeKind.Utc).AddTicks(8332),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Autohemoterapia Mayor"
                        },
                        new
                        {
                            Id = 4,
                            Cost = 1m,
                            CreatedUtc = new DateTime(2025, 2, 16, 16, 32, 18, 525, DateTimeKind.Utc).AddTicks(8333),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Autohemoterapia Menor"
                        },
                        new
                        {
                            Id = 5,
                            Cost = 1m,
                            CreatedUtc = new DateTime(2025, 2, 16, 16, 32, 18, 525, DateTimeKind.Utc).AddTicks(8334),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Biodescodificación"
                        },
                        new
                        {
                            Id = 6,
                            Cost = 1m,
                            CreatedUtc = new DateTime(2025, 2, 16, 16, 32, 18, 525, DateTimeKind.Utc).AddTicks(8335),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Biomagnetismo"
                        },
                        new
                        {
                            Id = 7,
                            Cost = 1m,
                            CreatedUtc = new DateTime(2025, 2, 16, 16, 32, 18, 525, DateTimeKind.Utc).AddTicks(8336),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Botox"
                        },
                        new
                        {
                            Id = 8,
                            Cost = 1m,
                            CreatedUtc = new DateTime(2025, 2, 16, 16, 32, 18, 525, DateTimeKind.Utc).AddTicks(8337),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Consulta De Fitomedicina"
                        },
                        new
                        {
                            Id = 9,
                            Cost = 1m,
                            CreatedUtc = new DateTime(2025, 2, 16, 16, 32, 18, 525, DateTimeKind.Utc).AddTicks(8338),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Consulta Estética"
                        },
                        new
                        {
                            Id = 10,
                            Cost = 1m,
                            CreatedUtc = new DateTime(2025, 2, 16, 16, 32, 18, 525, DateTimeKind.Utc).AddTicks(8338),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Consulta Homeopática"
                        },
                        new
                        {
                            Id = 11,
                            Cost = 1m,
                            CreatedUtc = new DateTime(2025, 2, 16, 16, 32, 18, 525, DateTimeKind.Utc).AddTicks(8383),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Consulta Traumatología"
                        },
                        new
                        {
                            Id = 12,
                            Cost = 1m,
                            CreatedUtc = new DateTime(2025, 2, 16, 16, 32, 18, 525, DateTimeKind.Utc).AddTicks(8384),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Consulta Via Online"
                        },
                        new
                        {
                            Id = 13,
                            Cost = 1m,
                            CreatedUtc = new DateTime(2025, 2, 16, 16, 32, 18, 525, DateTimeKind.Utc).AddTicks(8385),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Control De Continuador"
                        },
                        new
                        {
                            Id = 14,
                            Cost = 1m,
                            CreatedUtc = new DateTime(2025, 2, 16, 16, 32, 18, 525, DateTimeKind.Utc).AddTicks(8386),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Control Prenatal"
                        },
                        new
                        {
                            Id = 15,
                            Cost = 1m,
                            CreatedUtc = new DateTime(2025, 2, 16, 16, 32, 18, 525, DateTimeKind.Utc).AddTicks(8387),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Digitupuntura"
                        },
                        new
                        {
                            Id = 16,
                            Cost = 1m,
                            CreatedUtc = new DateTime(2025, 2, 16, 16, 32, 18, 525, DateTimeKind.Utc).AddTicks(8387),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Drenaje Linfático"
                        },
                        new
                        {
                            Id = 17,
                            Cost = 1m,
                            CreatedUtc = new DateTime(2025, 2, 16, 16, 32, 18, 525, DateTimeKind.Utc).AddTicks(8388),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Ecografía"
                        },
                        new
                        {
                            Id = 18,
                            Cost = 1m,
                            CreatedUtc = new DateTime(2025, 2, 16, 16, 32, 18, 525, DateTimeKind.Utc).AddTicks(8389),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Electroestimulación Muscular"
                        },
                        new
                        {
                            Id = 19,
                            Cost = 1m,
                            CreatedUtc = new DateTime(2025, 2, 16, 16, 32, 18, 525, DateTimeKind.Utc).AddTicks(8390),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Gineco-Obstetricia"
                        },
                        new
                        {
                            Id = 20,
                            Cost = 1m,
                            CreatedUtc = new DateTime(2025, 2, 16, 16, 32, 18, 525, DateTimeKind.Utc).AddTicks(8391),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Hilos Tensores"
                        },
                        new
                        {
                            Id = 21,
                            Cost = 1m,
                            CreatedUtc = new DateTime(2025, 2, 16, 16, 32, 18, 525, DateTimeKind.Utc).AddTicks(8391),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Laboratorio Clínico"
                        },
                        new
                        {
                            Id = 22,
                            Cost = 1m,
                            CreatedUtc = new DateTime(2025, 2, 16, 16, 32, 18, 525, DateTimeKind.Utc).AddTicks(8392),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Lavado Y Ozonoterapia Vaginal"
                        },
                        new
                        {
                            Id = 23,
                            Cost = 1m,
                            CreatedUtc = new DateTime(2025, 2, 16, 16, 32, 18, 525, DateTimeKind.Utc).AddTicks(8393),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Limpieza Facial Profunda"
                        },
                        new
                        {
                            Id = 24,
                            Cost = 1m,
                            CreatedUtc = new DateTime(2025, 2, 16, 16, 32, 18, 525, DateTimeKind.Utc).AddTicks(8394),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Lipotransferencia"
                        },
                        new
                        {
                            Id = 25,
                            Cost = 1m,
                            CreatedUtc = new DateTime(2025, 2, 16, 16, 32, 18, 525, DateTimeKind.Utc).AddTicks(8394),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Magnetoterapia"
                        },
                        new
                        {
                            Id = 26,
                            Cost = 1m,
                            CreatedUtc = new DateTime(2025, 2, 16, 16, 32, 18, 525, DateTimeKind.Utc).AddTicks(8395),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Masaje Descontracturante"
                        },
                        new
                        {
                            Id = 27,
                            Cost = 1m,
                            CreatedUtc = new DateTime(2025, 2, 16, 16, 32, 18, 525, DateTimeKind.Utc).AddTicks(8396),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Masaje Reductor"
                        },
                        new
                        {
                            Id = 28,
                            Cost = 1m,
                            CreatedUtc = new DateTime(2025, 2, 16, 16, 32, 18, 525, DateTimeKind.Utc).AddTicks(8396),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Masaje Relajante"
                        },
                        new
                        {
                            Id = 29,
                            Cost = 1m,
                            CreatedUtc = new DateTime(2025, 2, 16, 16, 32, 18, 525, DateTimeKind.Utc).AddTicks(8397),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Ozonoterapia Rectal"
                        },
                        new
                        {
                            Id = 30,
                            Cost = 1m,
                            CreatedUtc = new DateTime(2025, 2, 16, 16, 32, 18, 525, DateTimeKind.Utc).AddTicks(8398),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Papanicolau"
                        },
                        new
                        {
                            Id = 31,
                            Cost = 1m,
                            CreatedUtc = new DateTime(2025, 2, 16, 16, 32, 18, 525, DateTimeKind.Utc).AddTicks(8398),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Peeling Químico"
                        },
                        new
                        {
                            Id = 32,
                            Cost = 1m,
                            CreatedUtc = new DateTime(2025, 2, 16, 16, 32, 18, 525, DateTimeKind.Utc).AddTicks(8399),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Peptonas"
                        },
                        new
                        {
                            Id = 33,
                            Cost = 1m,
                            CreatedUtc = new DateTime(2025, 2, 16, 16, 32, 18, 525, DateTimeKind.Utc).AddTicks(8400),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Plasma Rico En Plaquetas"
                        },
                        new
                        {
                            Id = 34,
                            Cost = 1m,
                            CreatedUtc = new DateTime(2025, 2, 16, 16, 32, 18, 525, DateTimeKind.Utc).AddTicks(8401),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Podología"
                        },
                        new
                        {
                            Id = 35,
                            Cost = 1m,
                            CreatedUtc = new DateTime(2025, 2, 16, 16, 32, 18, 525, DateTimeKind.Utc).AddTicks(8401),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Quiropraxia"
                        },
                        new
                        {
                            Id = 36,
                            Cost = 1m,
                            CreatedUtc = new DateTime(2025, 2, 16, 16, 32, 18, 525, DateTimeKind.Utc).AddTicks(8402),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Radiofrecuencia"
                        },
                        new
                        {
                            Id = 37,
                            Cost = 1m,
                            CreatedUtc = new DateTime(2025, 2, 16, 16, 32, 18, 525, DateTimeKind.Utc).AddTicks(8403),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Suero Ozonizado"
                        },
                        new
                        {
                            Id = 38,
                            Cost = 1m,
                            CreatedUtc = new DateTime(2025, 2, 16, 16, 32, 18, 525, DateTimeKind.Utc).AddTicks(8404),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Terapia De Vitaminas"
                        },
                        new
                        {
                            Id = 39,
                            Cost = 1m,
                            CreatedUtc = new DateTime(2025, 2, 16, 16, 32, 18, 525, DateTimeKind.Utc).AddTicks(8405),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Terapia Física Y Rehabilitación"
                        },
                        new
                        {
                            Id = 40,
                            Cost = 1m,
                            CreatedUtc = new DateTime(2025, 2, 16, 16, 32, 18, 525, DateTimeKind.Utc).AddTicks(8405),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Terapia Neural"
                        },
                        new
                        {
                            Id = 41,
                            Cost = 1m,
                            CreatedUtc = new DateTime(2025, 2, 16, 16, 32, 18, 525, DateTimeKind.Utc).AddTicks(8406),
                            DurationMinutes = 30,
                            IsActive = true,
                            IsDeleted = false,
                            LastModifiedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Ultrasonido"
                        });
                });

            modelBuilder.Entity("Medical.Domain.Entities.TypeAppointment", b =>
                {
                    b.Property<int>("TypeAppointmentId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("TypeAppointmentId");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("[Name] IS NOT NULL");

                    b.ToTable("TypeAppointment");

                    b.HasData(
                        new
                        {
                            TypeAppointmentId = 0,
                            Name = "Consult"
                        },
                        new
                        {
                            TypeAppointmentId = 1,
                            Name = "Control"
                        });
                });

            modelBuilder.Entity("Medical.Domain.Entities.TypeDocument", b =>
                {
                    b.Property<int>("TypeDocumentId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("TypeDocumentId");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("[Name] IS NOT NULL");

                    b.ToTable("TypeDocument");

                    b.HasData(
                        new
                        {
                            TypeDocumentId = 0,
                            Name = "DNI"
                        },
                        new
                        {
                            TypeDocumentId = 1,
                            Name = "CI"
                        },
                        new
                        {
                            TypeDocumentId = 2,
                            Name = "CE"
                        },
                        new
                        {
                            TypeDocumentId = 3,
                            Name = "Passport"
                        });
                });

            modelBuilder.Entity("Medical.Domain.Entities.TypeSex", b =>
                {
                    b.Property<int>("TypeSexId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("TypeSexId");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("[Name] IS NOT NULL");

                    b.ToTable("TypeSex");

                    b.HasData(
                        new
                        {
                            TypeSexId = 0,
                            Name = "Female"
                        },
                        new
                        {
                            TypeSexId = 1,
                            Name = "Male"
                        });
                });

            modelBuilder.Entity("Medical.Domain.Entities.TypeShift", b =>
                {
                    b.Property<int>("TypeShiftId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("TypeShiftId");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("[Name] IS NOT NULL");

                    b.ToTable("TypeShift");

                    b.HasData(
                        new
                        {
                            TypeShiftId = 0,
                            Name = "Morning"
                        },
                        new
                        {
                            TypeShiftId = 1,
                            Name = "Afternoon"
                        },
                        new
                        {
                            TypeShiftId = 2,
                            Name = "Night"
                        });
                });

            modelBuilder.Entity("Medical.Domain.Entities.Appointment", b =>
                {
                    b.HasOne("Medical.Domain.Entities.Pacient", "Pacient")
                        .WithMany("Appointments")
                        .HasForeignKey("IdPacient")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Medical.Domain.Entities.Specialist", "Specialist")
                        .WithMany("Appointments")
                        .HasForeignKey("IdSpecialist")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Medical.Domain.Entities.Treatment", "Treatment")
                        .WithMany("Appointments")
                        .HasForeignKey("IdTreatment")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pacient");

                    b.Navigation("Specialist");

                    b.Navigation("Treatment");
                });

            modelBuilder.Entity("Medical.Domain.Entities.Pacient", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("Medical.Domain.Entities.Specialist", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("Medical.Domain.Entities.Treatment", b =>
                {
                    b.Navigation("Appointments");
                });
#pragma warning restore 612, 618
        }
    }
}
